services:
  - type: web
    name: claire
    region: frankfurt
    plan: pro
    runtime: docker
    dockerfilePath: ./Dockerfile
    # dockerCommand: docker run -d -p 3000:8080 -v claire:/app/backend/data --name claire --restart always
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    disk:
      name: storage
      mountPath: /app/backend/data
      sizeGB: 10