services:
  - type: web
    name: claire
    region: frankfurt
    plan: pro
    runtime: docker
    dockerfilePath: ./docker-compose.yaml
    dockerCommand: docker run -d -p 3000:8080 -v open-webui:/app/backend/data --name open-webui --restart always
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    disk:
      name: storage
      mountPath: /app/backend/data
      sizeGB: 10